### ISSUE TITLE
Yeoman Generator?

### ISSUE THREAD

**Issue by jagged3dge** [atSistemas/react-base#51]
It seems the yeoman generator templates are a part of the repo.

How soon would they be available to use with yeoman, as promised in the [Readme](https://github.com/atSistemas/react-base#overview)

**Comment by rafabernad** [comment]
Hi,

Our generator is pretty specific for componnent scaffolding in react-base in it's current state, so I'm not sure if it makes sense to publish it as a standalone generator right now.

Said that, you can use it inside any react-base project... just type:

`$ yo react-base`

**Comment by jagged3dge** [comment]
Ahh! I apologise for jumping the gun. I only now noticed the template folder in the project is linked via npm during the install script. Tyvm for your efforts! It seems a splendid boilerplate :+1:

**Comment by rafabernad** [comment]
Thanks! I assume we can now close this issue.

**Comment by jagged3dge** [comment]
I just encountered this error while using the Yeoman generator. I chose to build a component with the name `Backdrop`. This is what it spewed out. Note that this is right after the initial `npm install`.

```sh
D:\WampDeveloper\Websites\www.example.com\webroot\g4g-react-base (master)                                                                                                                             
λ yo react-base                                                                                                                                                                                       
? React-Base generator, choose your option:                                                                                                                                                           
 1- New Container                                                                                                                                                                                     
 2- New Component                                                                                                                                                                                     
  write you option:  2                                                                                                                                                                                
? Input Name Backdrop                                                                                                                                                                                 
   create app\components\Backdrop                                                                                                                                                                     
   create app\components\Backdrop\spec\Backdrop.component.spec.js                                                                                                                                     
D:\WampDeveloper\Websites\www.example.com\webroot\g4g-react-base\app\conf\.react-base\templates\generator-react-base\node_modules\mkdirp\index.js:92                                                  
                if (!stat.isDirectory()) throw err0;                                                                                                                                                  
                                         ^                                                                                                                                                            
                                                                                                                                                                                                      
Error: EEXIST: file already exists, mkdir 'D:\WampDeveloper\Websites\www.example.com\webroot\g4g-react-base\app\components\Backdrop'                                                                  
    at Error (native)                                                                                                                                                                                 
    at Object.fs.mkdirSync (fs.js:842:18)                                                                                                                                                             
    at sync (D:\WampDeveloper\Websites\www.example.com\webroot\g4g-react-base\app\conf\.react-base\templates\generator-react-base\node_modules\mkdirp\index.js:71:13)                                 
    at Function.sync (D:\WampDeveloper\Websites\www.example.com\webroot\g4g-react-base\app\conf\.react-base\templates\generator-react-base\node_modules\mkdirp\index.js:77:24)                        
    at write (D:\WampDeveloper\Websites\www.example.com\webroot\g4g-react-base\app\conf\.react-base\templates\generator-react-base\node_modules\mem-fs-editor\lib\actions\commit.js:12:12)            
    at DestroyableTransform._transform (D:\WampDeveloper\Websites\www.example.com\webroot\g4g-react-base\app\conf\.react-base\templates\generator-react-base\node_modules\mem-fs-editor\lib\actions\co
mmit.js:43:7)                                                                                                                                                                                         
    at DestroyableTransform.Transform._read (D:\WampDeveloper\Websites\www.example.com\webroot\g4g-react-base\app\conf\.react-base\templates\generator-react-base\node_modules\readable-stream\lib\_st
ream_transform.js:159:10)                                                                                                                                                                             
    at DestroyableTransform.Transform._write (D:\WampDeveloper\Websites\www.example.com\webroot\g4g-react-base\app\conf\.react-base\templates\generator-react-base\node_modules\readable-stream\lib\_s
tream_transform.js:147:83)                                                                                                                                                                            
    at doWrite (D:\WampDeveloper\Websites\www.example.com\webroot\g4g-react-base\app\conf\.react-base\templates\generator-react-base\node_modules\readable-stream\lib\_stream_writable.js:313:64)     
    at writeOrBuffer (D:\WampDeveloper\Websites\www.example.com\webroot\g4g-react-base\app\conf\.react-base\templates\generator-react-base\node_modules\readable-stream\lib\_stream_writable.js:302:5)
```

**Comment by jagged3dge** [comment]
I can see in [https://github.com/atSistemas/react-base/blob/master/app/conf/.react-base/templates/generator-react-base/generators/index.js#L116](https://github.com/atSistemas/react-base/blob/master/app/conf/.react-base/templates/generator-react-base/generators/index.js#L116), you're not adding any file extensions to the files being copied. Could it be the the file created in the `/*COMPONENT*/` section is being overwritten by the one created in the `/*STYLES*/` section?
Is this by design?

**Comment by jagged3dge** [comment]
I kinda fixed it by applying the following changes to the `createComponent` function in [https://github.com/atSistemas/react-base/blob/master/app/conf/.react-base/templates/generator-react-base/generators/index.js](https://github.com/atSistemas/react-base/blob/master/app/conf/.react-base/templates/generator-react-base/generators/index.js#L116)
```js
/*COMPONENT*/
...
  this.destinationPath(routeComponentName + typesDocument.component.nameFile), // <-- added nameFile reference
...
/*STYLES*/
...
  this.destinationPath(routeComponentName + typesDocument.styles.nameFile),  // <-- added nameFile reference
...
```

Thank you again for this stack & generator!

**Comment by luismartinez85** [comment]
Hi
bug about create a single component has been fixed, and will be incorporated in the master branch in the next release

thanks for report this issue
